version: "3.7"

services:
  mysql:
    container_name: todo_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=matheus_dantas
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=todo_db
    ports:
      - "3306:3306"
    volumes:
      - todo_mysql_data:/var/lib/mysql
  backend:
    container_name: todo-api
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - APP_ENV=development
      - APP_PORT=3000
    volumes:
      - ./src:/var/www/todo-api/src
      - ./test:/var/www/todo-api/test
    working_dir: /var/www/todo-api
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql

volumes:
  todo_mysql_data:

networks:
  default:
    external:
      name: todo-api
